// Đường dẫn: src/constants/airportData.ts

export interface AirportTranslation {
  city: string;
  country: string;
  name: string;
}

export const AIRPORT_MAPPING: Record<string, AirportTranslation> = {
  'ABJ': { city: 'Abidjan', country: 'Bờ Biển Ngà', name: 'Sân bay Félix-Houphouët-Boigny' },
  'ABQ': { city: 'Albuquerque', country: 'Mỹ', name: 'Sân bay Quốc tế Albuquerque' },
  'ABV': { city: 'Abuja', country: 'Nigeria', name: 'Sân bay Nnamdi Azikiwe' },
  'ACC': { city: 'Accra', country: 'Ghana', name: 'Sân bay Quốc tế Kotoka' },
  'ADB': { city: 'Izmir', country: 'Thổ Nhĩ Kỳ', name: 'Sân bay İzmir Adnan Menderes' },
  'ADD': { city: 'Addis Ababa', country: 'Ethiopia', name: 'Sân bay Addis Ababa Bole' },
  'ADL': { city: 'Adelaide', country: 'Úc', name: 'Sân bay Adelaide' },
  'AEP': { city: 'Buenos Aires', country: 'Argentina', name: 'Sân bay Aeroparque Jorge Newbery' },
  'AER': { city: 'Sochi', country: 'Nga', name: 'Sân bay Quốc tế Sochi' },
  'AGA': { city: 'Agadir', country: 'Ma-rốc', name: 'Sân bay Agadir–Al Massira' },
  'AGP': { city: 'Málaga', country: 'Tây Ban Nha', name: 'Sân bay Málaga' },
  'AKL': { city: 'Auckland', country: 'New Zealand', name: 'Sân bay Auckland' },
  'AKU': { city: 'Aksu', country: 'Trung Quốc', name: 'Sân bay Aksu' },
  'ALA': { city: 'Almaty', country: 'Kazakhstan', name: 'Sân bay Quốc tế Almaty' },
  'ALC': { city: 'Alicante', country: 'Tây Ban Nha', name: 'Sân bay Alicante-Elche' },
  'ALG': { city: 'Algiers', country: 'Algeria', name: 'Sân bay Houari Boumediene' },
  'AMD': { city: 'Ahmedabad', country: 'Ấn Độ', name: 'Sân bay Sardar Vallabhbhai Patel' },
  'AMM': { city: 'Amman', country: 'Jordan', name: 'Sân bay Quốc tế Nữ hoàng Alia' },
  'AMS': { city: 'Amsterdam', country: 'Hà Lan', name: 'Sân bay Amsterdam Schiphol' },
  'ANC': { city: 'Anchorage', country: 'Mỹ', name: 'Sân bay Ted Stevens Anchorage' },
  'APW': { city: 'Apia', country: 'Samoa', name: 'Sân bay Quốc tế Faleolo' },
  'AQP': { city: 'Arequipa', country: 'Peru', name: 'Sân bay Rodríguez Ballón' },
  'ARK': { city: 'Arusha', country: 'Tanzania', name: 'Sân bay Arusha' },
  'ARN': { city: 'Stockholm', country: 'Thụy Điển', name: 'Sân bay Stockholm Arlanda' },
  'ASE': { city: 'Aspen', country: 'Mỹ', name: 'Sân bay Pitkin County (Aspen)' },
  'ASU': { city: 'Asunción', country: 'Paraguay', name: 'Sân bay Quốc tế Silvio Pettirossi' },
  'ATH': { city: 'Athens', country: 'Hy Lạp', name: 'Sân bay Quốc tế Athens' },
  'ATL': { city: 'Atlanta', country: 'Mỹ', name: 'Sân bay Quốc tế Hartsfield-Jackson Atlanta' },
  'ATQ': { city: 'Amritsar', country: 'Ấn Độ', name: 'Sân bay Quốc tế Sri Guru Ram Dass Jee' },
  'AUA': { city: 'Aruba', country: 'Aruba', name: 'Sân bay Quốc tế Nữ hoàng Beatrix' },
  'AUH': { city: 'Abu Dhabi', country: 'UAE', name: 'Sân bay Quốc tế Zayed' },
  'AUS': { city: 'Austin', country: 'Mỹ', name: 'Sân bay Austin-Bergstrom' },
  'AVV': { city: 'Melbourne', country: 'Úc', name: 'Sân bay Avalon' },
  'AYT': { city: 'Antalya', country: 'Thổ Nhĩ Kỳ', name: 'Sân bay Antalya' },
  'BAH': { city: 'Manama', country: 'Bahrain', name: 'Sân bay Quốc tế Bahrain' },
  'BAQ': { city: 'Barranquilla', country: 'Colombia', name: 'Sân bay Ernesto Cortissoz' },
  'BBI': { city: 'Bhubaneswar', country: 'Ấn Độ', name: 'Sân bay Biju Patnaik' },
  'BCN': { city: 'Barcelona', country: 'Tây Ban Nha', name: 'Sân bay Barcelona-El Prat' },
  'BDO': { city: 'Bandung', country: 'Indonesia', name: 'Sân bay Husein Sastranegara' },
  'BEG': { city: 'Belgrade', country: 'Serbia', name: 'Sân bay Belgrade Nikola Tesla' },
  'BER': { city: 'Berlin', country: 'Đức', name: 'Sân bay Berlin Brandenburg' },
  'BEY': { city: 'Beirut', country: 'Lebanon', name: 'Sân bay Quốc tế Beirut-Rafic Hariri' },
  'BFM': { city: 'Mobile', country: 'Mỹ', name: 'Sân bay Mobile Downtown' },
  'BFS': { city: 'Belfast', country: 'Vương quốc Anh', name: 'Sân bay Quốc tế Belfast' },
  'BGI': { city: 'Bridgetown', country: 'Barbados', name: 'Sân bay Quốc tế Grantley Adams' },
  'BGO': { city: 'Bergen', country: 'Na Uy', name: 'Sân bay Bergen' },
  'BGW': { city: 'Baghdad', country: 'Iraq', name: 'Sân bay Quốc tế Baghdad' },
  'BGY': { city: 'Milan', country: 'Ý', name: 'Sân bay Orio al Serio (Bergamo)' },
  'BHD': { city: 'Belfast', country: 'Vương quốc Anh', name: 'Sân bay George Best Belfast City' },
  'BHE': { city: 'Blenheim', country: 'New Zealand', name: 'Sân bay Woodbourne' },
  'BHM': { city: 'Birmingham', country: 'Mỹ', name: 'Sân bay Quốc tế Birmingham-Shuttlesworth' },
  'BHX': { city: 'Birmingham', country: 'Vương quốc Anh', name: 'Sân bay Birmingham' },
  'BHY': { city: 'Bắc Hải', country: 'Trung Quốc', name: 'Sân bay Phúc Thành Bắc Hải' },
  'BIO': { city: 'Bilbao', country: 'Tây Ban Nha', name: 'Sân bay Bilbao' },
  'BJV': { city: 'Bodrum', country: 'Thổ Nhĩ Kỳ', name: 'Sân bay Milas-Bodrum' },
  'BJX': { city: 'León', country: 'Mexico', name: 'Sân bay Quốc tế Del Bajío' },
  'BKK': { city: 'Bangkok', country: 'Thái Lan', name: 'Sân bay Quốc tế Suvarnabhumi' },
  'BLL': { city: 'Billund', country: 'Đan Mạch', name: 'Sân bay Billund' },
  'BLQ': { city: 'Bologna', country: 'Ý', name: 'Sân bay Bologna Guglielmo Marconi' },
  'BLR': { city: 'Bangalore', country: 'Ấn Độ', name: 'Sân bay Quốc tế Kempegowda' },
  'BMA': { city: 'Stockholm', country: 'Thụy Điển', name: 'Sân bay Stockholm Bromma' },
  'BMV': { city: 'Buôn Ma Thuột', country: 'Việt Nam', name: 'Sân bay Buôn Ma Thuột' },
  'BNA': { city: 'Nashville', country: 'Mỹ', name: 'Sân bay Quốc tế Nashville' },
  'BNE': { city: 'Brisbane', country: 'Úc', name: 'Sân bay Brisbane' },
  'BOD': { city: 'Bordeaux', country: 'Pháp', name: 'Sân bay Bordeaux-Mérignac' },
  'BOG': { city: 'Bogotá', country: 'Colombia', name: 'Sân bay Quốc tế El Dorado' },
  'BOI': { city: 'Boise', country: 'Mỹ', name: 'Sân bay Boise' },
  'BOM': { city: 'Mumbai', country: 'Ấn Độ', name: 'Sân bay Quốc tế Chhatrapati Shivaji' },
  'BOS': { city: 'Boston', country: 'Mỹ', name: 'Sân bay Quốc tế Logan' },
  'BPN': { city: 'Balikpapan', country: 'Indonesia', name: 'Sân bay Sultan Aji Muhammad Sulaiman' },
  'BRC': { city: 'Bariloche', country: 'Argentina', name: 'Sân bay San Carlos de Bariloche' },
  'BRE': { city: 'Bremen', country: 'Đức', name: 'Sân bay Bremen' },
  'BRS': { city: 'Bristol', country: 'Vương quốc Anh', name: 'Sân bay Bristol' },
  'BRU': { city: 'Brussels', country: 'Bỉ', name: 'Sân bay Brussels' },
  'BSA': { city: 'Bossaso', country: 'Somalia', name: 'Sân bay Bossaso' },
  'BSB': { city: 'Brasília', country: 'Brazil', name: 'Sân bay Quốc tế Brasília' },
  'BSK': { city: 'Biskra', country: 'Algeria', name: 'Sân bay Mohamed Boudiaf' },
  'BSL': { city: 'Basel', country: 'Thụy Sĩ', name: 'Sân bay EuroAirport Basel Mulhouse' },
  'BSR': { city: 'Basra', country: 'Iraq', name: 'Sân bay Quốc tế Basra' },
  'BSZ': { city: 'Bartletts', country: 'Mỹ', name: 'Sân bay BSZ' },
  'BTR': { city: 'Baton Rouge', country: 'Mỹ', name: 'Sân bay Baton Rouge Metropolitan' },
  'BUD': { city: 'Budapest', country: 'Hungary', name: 'Sân bay Budapest Ferenc Liszt' },
  'BUF': { city: 'Buffalo', country: 'Mỹ', name: 'Sân bay Quốc tế Buffalo Niagara' },
  'BVA': { city: 'Paris', country: 'Pháp', name: 'Sân bay Paris Beauvais' },
  'BWI': { city: 'Baltimore', country: 'Mỹ', name: 'Sân bay Quốc tế Baltimore/Washington' },
  'BZE': { city: 'Belize City', country: 'Belize', name: 'Sân bay Quốc tế Philip S. W. Goldson' },
  'CAG': { city: 'Cagliari', country: 'Ý', name: 'Sân bay Cagliari Elmas' },
  'CAH': { city: 'Cà Mau', country: 'Việt Nam', name: 'Sân bay Cà Mau' },
  'CAI': { city: 'Cairo', country: 'Ai Cập', name: 'Sân bay Quốc tế Cairo' },
  'CAN': { city: 'Quảng Châu', country: 'Trung Quốc', name: 'Sân bay Bạch Vân Quảng Châu' },
  'CBR': { city: 'Canberra', country: 'Úc', name: 'Sân bay Canberra' },
  'CCJ': { city: 'Kozhikode', country: 'Ấn Độ', name: 'Sân bay Quốc tế Calicut' },
  'CCS': { city: 'Caracas', country: 'Venezuela', name: 'Sân bay Quốc tế Simón Bolívar' },
  'CCU': { city: 'Kolkata', country: 'Ấn Độ', name: 'Sân bay Quốc tế Netaji Subhas Chandra Bose' },
  'CDG': { city: 'Paris', country: 'Pháp', name: 'Sân bay Charles de Gaulle' },
  'CEI': { city: 'Chiang Rai', country: 'Thái Lan', name: 'Sân bay Mae Fah Luang - Chiang Rai' },
  'CFU': { city: 'Corfu', country: 'Hy Lạp', name: 'Sân bay Quốc tế Corfu' },
  'CGH': { city: 'São Paulo', country: 'Brazil', name: 'Sân bay São Paulo-Congonhas' },
  'CGN': { city: 'Cologne', country: 'Đức', name: 'Sân bay Cologne Bonn' },
  'CGO': { city: 'Trịnh Châu', country: 'Trung Quốc', name: 'Sân bay Quốc tế Tân Trịnh Trịnh Châu' },
  'CGP': { city: 'Chittagong', country: 'Bangladesh', name: 'Sân bay Shah Amanat' },
  'CGQ': { city: 'Trường Xuân', country: 'Trung Quốc', name: 'Sân bay Quốc tế Long Gia Trường Xuân' },
  'CHC': { city: 'Christchurch', country: 'New Zealand', name: 'Sân bay Quốc tế Christchurch' },
  'CIA': { city: 'Rome', country: 'Ý', name: 'Sân bay Ciampino' },
  'CIF': { city: 'Xích Phong', country: 'Trung Quốc', name: 'Sân bay Xích Phong' },
  'CJC': { city: 'Calama', country: 'Chile', name: 'Sân bay El Loa' },
  'CJJ': { city: 'Cheongju', country: 'Hàn Quốc', name: 'Sân bay Quốc tế Cheongju' },
  'CJU': { city: 'Jeju', country: 'Hàn Quốc', name: 'Sân bay Quốc tế Jeju' },
  'CKG': { city: 'Trùng Khánh', country: 'Trung Quốc', name: 'Sân bay Quốc tế Giang Bắc Trùng Khánh' },
  'CLE': { city: 'Cleveland', country: 'Mỹ', name: 'Sân bay Quốc tế Cleveland Hopkins' },
  'CLJ': { city: 'Cluj-Napoca', country: 'Romania', name: 'Sân bay Quốc tế Cluj' },
  'CLO': { city: 'Cali', country: 'Colombia', name: 'Sân bay Quốc tế Alfonso Bonilla Aragón' },
  'CLT': { city: 'Charlotte', country: 'Mỹ', name: 'Sân bay Quốc tế Charlotte Douglas' },
  'CLY': { city: 'Calvi', country: 'Pháp', name: 'Sân bay Calvi – Sainte-Catherine' },
  'CMB': { city: 'Colombo', country: 'Sri Lanka', name: 'Sân bay Quốc tế Bandaranaike' },
  'CMN': { city: 'Casablanca', country: 'Ma-rốc', name: 'Sân bay Quốc tế Mohammed V' },
  'CNF': { city: 'Belo Horizonte', country: 'Brazil', name: 'Sân bay Quốc tế Belo Horizonte' },
  'CNS': { city: 'Cairns', country: 'Úc', name: 'Sân bay Cairns' },
  'COK': { city: 'Kochi', country: 'Ấn Độ', name: 'Sân bay Quốc tế Cochin' },
  'COR': { city: 'Córdoba', country: 'Argentina', name: 'Sân bay Quốc tế Ingeniero Aeronáutico Ambrosio L.V. Taravella' },
  'CPH': { city: 'Copenhagen', country: 'Đan Mạch', name: 'Sân bay Copenhagen' },
  'CPT': { city: 'Cape Town', country: 'Nam Phi', name: 'Sân bay Quốc tế Cape Town' },
  'CRL': { city: 'Brussels', country: 'Bỉ', name: 'Sân bay Brussels South Charleroi' },
  'CSG': { city: 'Columbus', country: 'Mỹ', name: 'Sân bay Columbus Metropolitan' },
  'CSX': { city: 'Trường Sa', country: 'Trung Quốc', name: 'Sân bay Quốc tế Hoàng Hoa Trường Sa' },
  'CTA': { city: 'Catania', country: 'Ý', name: 'Sân bay Catania-Fontanarossa' },
  'CTG': { city: 'Cartagena', country: 'Colombia', name: 'Sân bay Quốc tế Rafael Núñez' },
  'CTS': { city: 'Sapporo', country: 'Nhật Bản', name: 'Sân bay New Chitose' },
  'CTU': { city: 'Thành Đô', country: 'Trung Quốc', name: 'Sân bay Quốc tế Song Lưu Thành Đô' },
  'CUN': { city: 'Cancún', country: 'Mexico', name: 'Sân bay Quốc tế Cancún' },
  'CUR': { city: 'Curaçao', country: 'Curaçao', name: 'Sân bay Quốc tế Curaçao' },
  'CUZ': { city: 'Cusco', country: 'Peru', name: 'Sân bay Quốc tế Alejandro Velasco Astete' },
  'CVG': { city: 'Cincinnati', country: 'Mỹ', name: 'Sân bay Quốc tế Cincinnati/Northern Kentucky' },
  'CWB': { city: 'Curitiba', country: 'Brazil', name: 'Sân bay Quốc tế Afonso Pena' },
  'CXR': { city: 'Nha Trang', country: 'Việt Nam', name: 'Sân bay Quốc tế Cam Ranh' },
  'DAC': { city: 'Dhaka', country: 'Bangladesh', name: 'Sân bay Quốc tế Hazrat Shahjalal' },
  'DAD': { city: 'Đà Nẵng', country: 'Việt Nam', name: 'Sân bay Quốc tế Đà Nẵng' },
  'DAL': { city: 'Dallas', country: 'Mỹ', name: 'Sân bay Dallas Love Field' },
  'DAR': { city: 'Dar es Salaam', country: 'Tanzania', name: 'Sân bay Quốc tế Julius Nyerere' },
  'DBV': { city: 'Dubrovnik', country: 'Croatia', name: 'Sân bay Dubrovnik' },
  'DCA': { city: 'Washington D.C.', country: 'Mỹ', name: 'Sân bay Quốc gia Ronald Reagan Washington' },
  'DEL': { city: 'Delhi', country: 'Ấn Độ', name: 'Sân bay Quốc tế Indira Gandhi' },
  'DEN': { city: 'Denver', country: 'Mỹ', name: 'Sân bay Quốc tế Denver' },
  'DFW': { city: 'Dallas', country: 'Mỹ', name: 'Sân bay Quốc tế Dallas/Fort Worth' },
  'DGE': { city: 'Mudgee', country: 'Úc', name: 'Sân bay Mudgee' },
  'DIL': { city: 'Dili', country: 'Đông Timor', name: 'Sân bay Quốc tế Presidente Nicolau Lobato' },
  'DIN': { city: 'Điện Biên Phủ', country: 'Việt Nam', name: 'Sân bay Điện Biên Phủ' },
  'DJE': { city: 'Djerba', country: 'Tunisia', name: 'Sân bay Quốc tế Djerba-Zarzis' },
  'DKR': { city: 'Dakar', country: 'Senegal', name: 'Sân bay Quốc tế Blaise Diagne' },
  'DLA': { city: 'Douala', country: 'Cameroon', name: 'Sân bay Quốc tế Douala' },
  'DLC': { city: 'Đại Liên', country: 'Trung Quốc', name: 'Sân bay Quốc tế Chu Thủy Tử Đại Liên' },
  'DLI': { city: 'Đà Lạt', country: 'Việt Nam', name: 'Sân bay Liên Khương' },
  'DLM': { city: 'Dalaman', country: 'Thổ Nhĩ Kỳ', name: 'Sân bay Dalaman' },
  'DME': { city: 'Moscow', country: 'Nga', name: 'Sân bay Quốc tế Domodedovo' },
  'DMK': { city: 'Bangkok', country: 'Thái Lan', name: 'Sân bay Quốc tế Don Mueang' },
  'DMM': { city: 'Dammam', country: 'Ả Rập Xê Út', name: 'Sân bay Quốc tế King Fahd' },
  'DOH': { city: 'Doha', country: 'Qatar', name: 'Sân bay Quốc tế Hamad' },
  'DRW': { city: 'Darwin', country: 'Úc', name: 'Sân bay Quốc tế Darwin' },
  'DSS': { city: 'Dakar', country: 'Senegal', name: 'Sân bay Quốc tế Blaise Diagne' },
  'DTW': { city: 'Detroit', country: 'Mỹ', name: 'Sân bay Detroit Metropolitan' },
  'DUB': { city: 'Dublin', country: 'Ireland', name: 'Sân bay Dublin' },
  'DUN': { city: 'Dunedin', country: 'New Zealand', name: 'Sân bay Dunedin' },
  'DUR': { city: 'Durban', country: 'Nam Phi', name: 'Sân bay Quốc tế King Shaka' },
  'DUS': { city: 'Düsseldorf', country: 'Đức', name: 'Sân bay Düsseldorf' },
  'DVO': { city: 'Davao', country: 'Philippines', name: 'Sân bay Quốc tế Francisco Bangoy' },
  'DWC': { city: 'Dubai', country: 'UAE', name: 'Sân bay Quốc tế Al Maktoum' },
  'DXB': { city: 'Dubai', country: 'UAE', name: 'Sân bay Quốc tế Dubai' },
  'DYG': { city: 'Trương Gia Giới', country: 'Trung Quốc', name: 'Sân bay Hà Hoa Trương Gia Giới' },
  'DYU': { city: 'Dushanbe', country: 'Tajikistan', name: 'Sân bay Quốc tế Dushanbe' },
  'EAS': { city: 'San Sebastián', country: 'Tây Ban Nha', name: 'Sân bay Donostia - San Sebastian' },
  'EBB': { city: 'Entebbe', country: 'Uganda', name: 'Sân bay Quốc tế Entebbe' },
  'EBL': { city: 'Erbil', country: 'Iraq', name: 'Sân bay Quốc tế Erbil' },
  'EDI': { city: 'Edinburgh', country: 'Vương quốc Anh', name: 'Sân bay Edinburgh' },
  'EIN': { city: 'Eindhoven', country: 'Hà Lan', name: 'Sân bay Eindhoven' },
  'EMA': { city: 'East Midlands', country: 'Vương quốc Anh', name: 'Sân bay East Midlands' },
  'ENI': { city: 'El Nido', country: 'Philippines', name: 'Sân bay Lio (ENI)' },
  'ESB': { city: 'Ankara', country: 'Thổ Nhĩ Kỳ', name: 'Sân bay Ankara Esenboğa' },
  'EVN': { city: 'Yerevan', country: 'Armenia', name: 'Sân bay Quốc tế Zvartnots' },
  'EWR': { city: 'Newark', country: 'Mỹ', name: 'Sân bay Quốc tế Newark Liberty' },
  'EZE': { city: 'Buenos Aires', country: 'Argentina', name: 'Sân bay Quốc tế Ministro Pistarini' },
  'FAO': { city: 'Faro', country: 'Bồ Đào Nha', name: 'Sân bay Faro' },
  'FCO': { city: 'Rome', country: 'Ý', name: 'Sân bay Leonardo da Vinci-Fiumicino' },
  'FDF': { city: 'Fort-de-France', country: 'Martinique', name: 'Sân bay Quốc tế Martinique Aimé Césaire' },
  'FIH': { city: 'Kinshasa', country: 'CHDC Congo', name: 'Sân bay Quốc tế N\'djili' },
  'FLL': { city: 'Fort Lauderdale', country: 'Mỹ', name: 'Sân bay Quốc tế Fort Lauderdale–Hollywood' },
  'FLN': { city: 'Florianópolis', country: 'Brazil', name: 'Sân bay Quốc tế Hercílio Luz' },
  'FLR': { city: 'Florence', country: 'Ý', name: 'Sân bay Florence' },
  'FNC': { city: 'Madeira', country: 'Bồ Đào Nha', name: 'Sân bay Madeira' },
  'FOC': { city: 'Phúc Châu', country: 'Trung Quốc', name: 'Sân bay Quốc tế Trường Lạc Phúc Châu' },
  'FOR': { city: 'Fortaleza', country: 'Brazil', name: 'Sân bay Quốc tế Pinto Martins' },
  'FRA': { city: 'Frankfurt', country: 'Đức', name: 'Sân bay Frankfurt' },
  'FSZ': { city: 'Shizuoka', country: 'Nhật Bản', name: 'Sân bay Mt. Fuji Shizuoka' },
  'FUK': { city: 'Fukuoka', country: 'Nhật Bản', name: 'Sân bay Fukuoka' },
  'FYN': { city: 'Phú Uẩn', country: 'Trung Quốc', name: 'Sân bay Khả Khắc Đạt Lạp Phú Uẩn' },
  'GAU': { city: 'Guwahati', country: 'Ấn Độ', name: 'Sân bay Quốc tế Lokpriya Gopinath Bordoloi' },
  'GDL': { city: 'Guadalajara', country: 'Mexico', name: 'Sân bay Quốc tế Guadalajara' },
  'GDN': { city: 'Gdańsk', country: 'Ba Lan', name: 'Sân bay Gdańsk Lech Wałęsa' },
  'GIG': { city: 'Rio de Janeiro', country: 'Brazil', name: 'Sân bay Quốc tế Rio Galeão-Tom Jobim' },
  'GLA': { city: 'Glasgow', country: 'Vương quốc Anh', name: 'Sân bay Glasgow' },
  'GLT': { city: 'Gladstone', country: 'Úc', name: 'Sân bay Gladstone' },
  'GMP': { city: 'Seoul', country: 'Hàn Quốc', name: 'Sân bay Quốc tế Gimpo' },
  'GOA': { city: 'Genoa', country: 'Ý', name: 'Sân bay Genoa Cristoforo Colombo' },
  'GOI': { city: 'Goa', country: 'Ấn Độ', name: 'Sân bay Quốc tế Dabolim' },
  'GOT': { city: 'Gothenburg', country: 'Thụy Điển', name: 'Sân bay Göteborg Landvetter' },
  'GOX': { city: 'Goa', country: 'Ấn Độ', name: 'Sân bay Quốc tế Manohar' },
  'GRU': { city: 'São Paulo', country: 'Brazil', name: 'Sân bay Quốc tế São Paulo-Guarulhos' },
  'GUA': { city: 'Guatemala City', country: 'Guatemala', name: 'Sân bay Quốc tế La Aurora' },
  'GUM': { city: 'Guam', country: 'Guam', name: 'Sân bay Quốc tế Antonio B. Won Pat' },
  'GVA': { city: 'Geneva', country: 'Thụy Sĩ', name: 'Sân bay Geneva' },
  'GYD': { city: 'Baku', country: 'Azerbaijan', name: 'Sân bay Quốc tế Heydar Aliyev' },
  'GYE': { city: 'Guayaquil', country: 'Ecuador', name: 'Sân bay Quốc tế José Joaquín de Olmedo' },
  'GYS': { city: 'Quảng Nguyên', country: 'Trung Quốc', name: 'Sân bay Quảng Nguyên Bàn Long' },
  'GZP': { city: 'Gazipaşa', country: 'Thổ Nhĩ Kỳ', name: 'Sân bay Gazipaşa-Alanya' },
  'HAJ': { city: 'Hanover', country: 'Đức', name: 'Sân bay Hannover' },
  'HAK': { city: 'Hải Khẩu', country: 'Trung Quốc', name: 'Sân bay Quốc tế Mỹ Lan Hải Khẩu' },
  'HAM': { city: 'Hamburg', country: 'Đức', name: 'Sân bay Hamburg' },
  'HAN': { city: 'Hà Nội', country: 'Việt Nam', name: 'Sân bay Quốc tế Nội Bài' },
  'HAV': { city: 'Havana', country: 'Cuba', name: 'Sân bay Quốc tế José Martí' },
  'HBA': { city: 'Hobart', country: 'Úc', name: 'Sân bay Hobart' },
  'HBE': { city: 'Alexandria', country: 'Ai Cập', name: 'Sân bay Quốc tế Borg El Arab' },
  'HDY': { city: 'Hat Yai', country: 'Thái Lan', name: 'Sân bay Quốc tế Hat Yai' },
  'HEL': { city: 'Helsinki', country: 'Phần Lan', name: 'Sân bay Helsinki' },
  'HER': { city: 'Heraklion', country: 'Hy Lạp', name: 'Sân bay Quốc tế Heraklion' },
  'HET': { city: 'Hô Hòa Hạo Đặc', country: 'Trung Quốc', name: 'Sân bay Quốc tế Bạch Tháp Hô Hòa Hạo Đặc' },
  'HGH': { city: 'Hàng Châu', country: 'Trung Quốc', name: 'Sân bay Quốc tế Tiêu Sơn Hàng Châu' },
  'HIJ': { city: 'Hiroshima', country: 'Nhật Bản', name: 'Sân bay Hiroshima' },
  'HKD': { city: 'Hakodate', country: 'Nhật Bản', name: 'Sân bay Hakodate' },
  'HKG': { city: 'Hồng Kông', country: 'Hồng Kông', name: 'Sân bay Quốc tế Hồng Kông' },
  'HKT': { city: 'Phuket', country: 'Thái Lan', name: 'Sân bay Quốc tế Phuket' },
  'HLA': { city: 'Johannesburg', country: 'Nam Phi', name: 'Sân bay Quốc tế Lanseria' },
  'HND': { city: 'Tokyo', country: 'Nhật Bản', name: 'Sân bay Quốc tế Tokyo Haneda' },
  'HNL': { city: 'Honolulu', country: 'Mỹ', name: 'Sân bay Quốc tế Daniel K. Inouye' },
  'HOU': { city: 'Houston', country: 'Mỹ', name: 'Sân bay William P. Hobby' },
  'HPH': { city: 'Hải Phòng', country: 'Việt Nam', name: 'Sân bay Quốc tế Cát Bi' },
  'HRB': { city: 'Cáp Nhĩ Tân', country: 'Trung Quốc', name: 'Sân bay Quốc tế Thái Bình Cáp Nhĩ Tân' },
  'HRG': { city: 'Hurghada', country: 'Ai Cập', name: 'Sân bay Quốc tế Hurghada' },
  'HUI': { city: 'Huế', country: 'Việt Nam', name: 'Sân bay Quốc tế Phú Bài' },
  'HYD': { city: 'Hyderabad', country: 'Ấn Độ', name: 'Sân bay Quốc tế Rajiv Gandhi' },
  'IAD': { city: 'Washington D.C.', country: 'Mỹ', name: 'Sân bay Quốc tế Washington Dulles' },
  'IAH': { city: 'Houston', country: 'Mỹ', name: 'Sân bay Xuyên lục địa George Bush' },
  'IBZ': { city: 'Ibiza', country: 'Tây Ban Nha', name: 'Sân bay Ibiza' },
  'ICN': { city: 'Seoul', country: 'Hàn Quốc', name: 'Sân bay Quốc tế Incheon' },
  'IGU': { city: 'Foz do Iguaçu', country: 'Brazil', name: 'Sân bay Quốc tế Foz do Iguaçu/Cataratas' },
  'IKA': { city: 'Tehran', country: 'Iran', name: 'Sân bay Quốc tế Imam Khomeini' },
  'ILO': { city: 'Iloilo', country: 'Philippines', name: 'Sân bay Quốc tế Iloilo' },
  'IND': { city: 'Indianapolis', country: 'Mỹ', name: 'Sân bay Quốc tế Indianapolis' },
  'INN': { city: 'Innsbruck', country: 'Áo', name: 'Sân bay Innsbruck' },
  'ISB': { city: 'Islamabad', country: 'Pakistan', name: 'Sân bay Quốc tế Islamabad' },
  'ISG': { city: 'Ishigaki', country: 'Nhật Bản', name: 'Sân bay New Ishigaki' },
  'IST': { city: 'Istanbul', country: 'Thổ Nhĩ Kỳ', name: 'Sân bay Istanbul' },
  'ITM': { city: 'Osaka', country: 'Nhật Bản', name: 'Sân bay Quốc tế Osaka (Itami)' },
  'IXE': { city: 'Mangalore', country: 'Ấn Độ', name: 'Sân bay Quốc tế Mangalore' },
  'JAX': { city: 'Jacksonville', country: 'Mỹ', name: 'Sân bay Quốc tế Jacksonville' },
  'JED': { city: 'Jeddah', country: 'Ả Rập Xê Út', name: 'Sân bay Quốc tế King Abdulaziz' },
  'JFK': { city: 'New York', country: 'Mỹ', name: 'Sân bay Quốc tế John F. Kennedy' },
  'JIB': { city: 'Djibouti', country: 'Djibouti', name: 'Sân bay Quốc tế Djibouti-Ambouli' },
  'JJN': { city: 'Tuyền Châu', country: 'Trung Quốc', name: 'Sân bay Quốc tế Tấn Giang Tuyền Châu' },
  'JMK': { city: 'Mykonos', country: 'Hy Lạp', name: 'Sân bay Quốc gia Đảo Mykonos' },
  'JNB': { city: 'Johannesburg', country: 'Nam Phi', name: 'Sân bay Quốc tế O. R. Tambo' },
  'JOG': { city: 'Yogyakarta', country: 'Indonesia', name: 'Sân bay Quốc tế Adisutjipto' },
  'JTR': { city: 'Santorini', country: 'Hy Lạp', name: 'Sân bay Quốc gia Santorini (Thira)' },
  'KBL': { city: 'Kabul', country: 'Afghanistan', name: 'Sân bay Quốc tế Kabul' },
  'KEF': { city: 'Reykjavík', country: 'Iceland', name: 'Sân bay Quốc tế Keflavík' },
  'KGL': { city: 'Kigali', country: 'Rwanda', name: 'Sân bay Quốc tế Kigali' },
  'KGS': { city: 'Kos', country: 'Hy Lạp', name: 'Sân bay Quốc tế Đảo Kos' },
  'KHG': { city: 'Kashgar (Khách Thập)', country: 'Trung Quốc', name: 'Sân bay Kashgar' },
  'KHH': { city: 'Cao Hùng', country: 'Đài Loan', name: 'Sân bay Quốc tế Cao Hùng' },
  'KHI': { city: 'Karachi', country: 'Pakistan', name: 'Sân bay Quốc tế Jinnah' },
  'KIJ': { city: 'Niigata', country: 'Nhật Bản', name: 'Sân bay Niigata' },
  'KIN': { city: 'Kingston', country: 'Jamaica', name: 'Sân bay Quốc tế Norman Manley' },
  'KIX': { city: 'Osaka', country: 'Nhật Bản', name: 'Sân bay Quốc tế Kansai' },
  'KLO': { city: 'Kalibo', country: 'Philippines', name: 'Sân bay Quốc tế Kalibo' },
  'KMG': { city: 'Côn Minh', country: 'Trung Quốc', name: 'Sân bay Quốc tế Trường Thủy Côn Minh' },
  'KMJ': { city: 'Kumamoto', country: 'Nhật Bản', name: 'Sân bay Kumamoto' },
  'KMQ': { city: 'Komatsu', country: 'Nhật Bản', name: 'Sân bay Komatsu' },
  'KNO': { city: 'Medan', country: 'Indonesia', name: 'Sân bay Quốc tế Kualanamu (Polonia cũ)' },
  'KOJ': { city: 'Kagoshima', country: 'Nhật Bản', name: 'Sân bay Kagoshima' },
  'KQH': { city: 'Kishangarh', country: 'Ấn Độ', name: 'Sân bay Kishangarh' },
  'KRK': { city: 'Kraków', country: 'Ba Lan', name: 'Sân bay Quốc tế John Paul II Kraków-Balice' },
  'KSN': { city: 'Kostanay', country: 'Kazakhstan', name: 'Sân bay Quốc tế Kostanay' },
  'KTM': { city: 'Kathmandu', country: 'Nepal', name: 'Sân bay Quốc tế Tribhuvan' },
  'KTW': { city: 'Katowice', country: 'Ba Lan', name: 'Sân bay Quốc tế Katowice' },
  'KUL': { city: 'Kuala Lumpur', country: 'Malaysia', name: 'Sân bay Quốc tế Kuala Lumpur (KLIA)' },
  'KUS': { city: 'Kulusuk', country: 'Greenland', name: 'Sân bay Kulusuk' },
  'KWE': { city: 'Quý Dương', country: 'Trung Quốc', name: 'Sân bay Quốc tế Long Động Bảo Quý Dương' },
  'KWI': { city: 'Thành phố Kuwait', country: 'Kuwait', name: 'Sân bay Quốc tế Kuwait' },
  'LAD': { city: 'Luanda', country: 'Angola', name: 'Sân bay Quốc tế Quatro de Fevereiro' },
  'LAS': { city: 'Las Vegas', country: 'Mỹ', name: 'Sân bay Quốc tế Harry Reid' },
  'LAX': { city: 'Los Angeles', country: 'Mỹ', name: 'Sân bay Quốc tế Los Angeles' },
  'LBA': { city: 'Leeds/Bradford', country: 'Vương quốc Anh', name: 'Sân bay Leeds Bradford' },
  'LCA': { city: 'Larnaca', country: 'Síp', name: 'Sân bay Quốc tế Larnaca' },
  'LED': { city: 'Saint Petersburg', country: 'Nga', name: 'Sân bay Pulkovo' },
  'LEJ': { city: 'Leipzig/Halle', country: 'Đức', name: 'Sân bay Leipzig/Halle' },
  'LFT': { city: 'Lafayette', country: 'Mỹ', name: 'Sân bay Khu vực Lafayette' },
  'LFW': { city: 'Lomé', country: 'Togo', name: 'Sân bay Quốc tế Gnassingbé Eyadéma' },
  'LGA': { city: 'New York', country: 'Mỹ', name: 'Sân bay LaGuardia' },
  'LGW': { city: 'London', country: 'Vương quốc Anh', name: 'Sân bay Gatwick' },
  'LHE': { city: 'Lahore', country: 'Pakistan', name: 'Sân bay Quốc tế Allama Iqbal' },
  'LHR': { city: 'London', country: 'Vương quốc Anh', name: 'Sân bay Heathrow' },
  'LHW': { city: 'Lan Châu', country: 'Trung Quốc', name: 'Sân bay Quốc tế Trung Xuyên Lan Châu' },
  'LIL': { city: 'Lille', country: 'Pháp', name: 'Sân bay Lille' },
  'LIM': { city: 'Lima', country: 'Peru', name: 'Sân bay Quốc tế Jorge Chávez' },
  'LIN': { city: 'Milan', country: 'Ý', name: 'Sân bay Linate' },
  'LIR': { city: 'Liberia', country: 'Costa Rica', name: 'Sân bay Quốc tế Guanacaste' },
  'LIS': { city: 'Lisbon', country: 'Bồ Đào Nha', name: 'Sân bay Lisbon' },
  'LJU': { city: 'Ljubljana', country: 'Slovenia', name: 'Sân bay Ljubljana Jože Pučnik' },
  'LKO': { city: 'Lucknow', country: 'Ấn Độ', name: 'Sân bay Quốc tế Chaudhary Charan Singh' },
  'LOS': { city: 'Lagos', country: 'Nigeria', name: 'Sân bay Quốc tế Murtala Muhammed' },
  'LPA': { city: 'Gran Canaria', country: 'Tây Ban Nha', name: 'Sân bay Gran Canaria' },
  'LPB': { city: 'La Paz', country: 'Bolivia', name: 'Sân bay Quốc tế El Alto' },
  'LPQ': { city: 'Luang Prabang', country: 'Lào', name: 'Sân bay Quốc tế Luang Prabang' },
  'LST': { city: 'Launceston', country: 'Úc', name: 'Sân bay Launceston' },
  'LTN': { city: 'London', country: 'Vương quốc Anh', name: 'Sân bay Luton' },
  'LXA': { city: 'Lhasa', country: 'Trung Quốc', name: 'Sân bay Cống Dát Lhasa' },
  'LXR': { city: 'Luxor', country: 'Ai Cập', name: 'Sân bay Quốc tế Luxor' },
  'LYS': { city: 'Lyon', country: 'Pháp', name: 'Sân bay Lyon-Saint Exupéry' },
  'MAA': { city: 'Chennai', country: 'Ấn Độ', name: 'Sân bay Quốc tế Chennai' },
  'MAD': { city: 'Madrid', country: 'Tây Ban Nha', name: 'Sân bay Adolfo Suárez Madrid-Barajas' },
  'MAN': { city: 'Manchester', country: 'Vương quốc Anh', name: 'Sân bay Manchester' },
  'MAO': { city: 'Manaus', country: 'Brazil', name: 'Sân bay Quốc tế Eduardo Gomes' },
  'MAR': { city: 'Maracaibo', country: 'Venezuela', name: 'Sân bay Quốc tế La Chinita' },
  'MBA': { city: 'Mombasa', country: 'Kenya', name: 'Sân bay Quốc tế Moi' },
  'MBJ': { city: 'Montego Bay', country: 'Jamaica', name: 'Sân bay Quốc tế Sangster' },
  'MCI': { city: 'Kansas City', country: 'Mỹ', name: 'Sân bay Quốc tế Kansas City' },
  'MCO': { city: 'Orlando', country: 'Mỹ', name: 'Sân bay Quốc tế Orlando' },
  'MCT': { city: 'Muscat', country: 'Oman', name: 'Sân bay Quốc tế Muscat' },
  'MDE': { city: 'Medellín', country: 'Colombia', name: 'Sân bay Quốc tế José María Córdova' },
  'MDL': { city: 'Mandalay', country: 'Myanmar', name: 'Sân bay Quốc tế Mandalay' },
  'MDW': { city: 'Chicago', country: 'Mỹ', name: 'Sân bay Quốc tế Chicago Midway' },
  'MDZ': { city: 'Mendoza', country: 'Argentina', name: 'Sân bay Quốc tế Governor Francisco Gabrielli' },
  'MED': { city: 'Medina', country: 'Ả Rập Xê Út', name: 'Sân bay Quốc tế Prince Mohammad bin Abdulaziz' },
  'MEL': { city: 'Melbourne', country: 'Úc', name: 'Sân bay Melbourne' },
  'MEM': { city: 'Memphis', country: 'Mỹ', name: 'Sân bay Quốc tế Memphis' },
  'MEX': { city: 'Thành phố Mexico', country: 'Mexico', name: 'Sân bay Quốc tế Thành phố Mexico' },
  'MFM': { city: 'Macau', country: 'Macau', name: 'Sân bay Quốc tế Macau' },
  'MGA': { city: 'Managua', country: 'Nicaragua', name: 'Sân bay Quốc tế Augusto C. Sandino' },
  'MHD': { city: 'Mashhad', country: 'Iran', name: 'Sân bay Quốc tế Mashhad' },
  'MIA': { city: 'Miami', country: 'Mỹ', name: 'Sân bay Quốc tế Miami' },
  'MID': { city: 'Mérida', country: 'Mexico', name: 'Sân bay Quốc tế Mérida' },
  'MKE': { city: 'Milwaukee', country: 'Mỹ', name: 'Sân bay Quốc tế Milwaukee Mitchell' },
  'MKY': { city: 'Mackay', country: 'Úc', name: 'Sân bay Mackay' },
  'MLE': { city: 'Malé', country: 'Maldives', name: 'Sân bay Quốc tế Velana' },
  'MMX': { city: 'Malmö', country: 'Thụy Điển', name: 'Sân bay Malmö' },
  'MMY': { city: 'Miyakojima', country: 'Nhật Bản', name: 'Sân bay Miyako' },
  'MNL': { city: 'Manila', country: 'Philippines', name: 'Sân bay Quốc tế Ninoy Aquino' },
  'MOB': { city: 'Mobile', country: 'Mỹ', name: 'Sân bay Khu vực Mobile' },
  'MRS': { city: 'Marseille', country: 'Pháp', name: 'Sân bay Marseille Provence' },
  'MRU': { city: 'Port Louis', country: 'Mauritius', name: 'Sân bay Quốc tế Sir Seewoosagur Ramgoolam' },
  'MSJ': { city: 'Misawa', country: 'Nhật Bản', name: 'Sân bay Misawa' },
  'MSP': { city: 'Minneapolis-St. Paul', country: 'Mỹ', name: 'Sân bay Quốc tế Minneapolis-Saint Paul' },
  'MSY': { city: 'New Orleans', country: 'Mỹ', name: 'Sân bay Quốc tế Louis Armstrong New Orleans' },
  'MTY': { city: 'Monterrey', country: 'Mexico', name: 'Sân bay Quốc tế Monterrey' },
  'MUC': { city: 'Munich', country: 'Đức', name: 'Sân bay Munich' },
  'MVD': { city: 'Montevideo', country: 'Uruguay', name: 'Sân bay Quốc tế Carrasco' },
  'MWX': { city: 'Muan', country: 'Hàn Quốc', name: 'Sân bay Quốc tế Muan' },
  'MXP': { city: 'Milan', country: 'Ý', name: 'Sân bay Milan Malpensa' },
  'MYJ': { city: 'Matsuyama', country: 'Nhật Bản', name: 'Sân bay Matsuyama' },
  'NAJ': { city: 'Nakhchivan', country: 'Azerbaijan', name: 'Sân bay Quốc tế Nakhchivan' },
  'NAN': { city: 'Nadi', country: 'Fiji', name: 'Sân bay Quốc tế Nadi' },
  'NAP': { city: 'Naples', country: 'Ý', name: 'Sân bay Quốc tế Naples' },
  'NAS': { city: 'Nassau', country: 'Bahamas', name: 'Sân bay Quốc tế Lynden Pindling' },
  'NBE': { city: 'Enfidha', country: 'Tunisia', name: 'Sân bay Quốc tế Enfidha-Hammamet' },
  'NBO': { city: 'Nairobi', country: 'Kenya', name: 'Sân bay Quốc tế Jomo Kenyatta' },
  'NCE': { city: 'Nice', country: 'Pháp', name: 'Sân bay Nice Côte d\'Azur' },
  'NCL': { city: 'Newcastle', country: 'Vương quốc Anh', name: 'Sân bay Quốc tế Newcastle' },
  'NGB': { city: 'Ninh Ba', country: 'Trung Quốc', name: 'Sân bay Quốc tế Lịch Xã Ninh Ba' },
  'NGO': { city: 'Nagoya', country: 'Nhật Bản', name: 'Sân bay Quốc tế Chubu Centrair' },
  'NGS': { city: 'Nagasaki', country: 'Nhật Bản', name: 'Sân bay Nagasaki' },
  'NKG': { city: 'Nam Kinh', country: 'Trung Quốc', name: 'Sân bay Quốc tế Lộc Khẩu Nam Kinh' },
  'NOU': { city: 'Nouméa', country: 'New Caledonia', name: 'Sân bay Quốc tế La Tontouta' },
  'NQZ': { city: 'Astana', country: 'Kazakhstan', name: 'Sân bay Quốc tế Nursultan Nazarbayev' },
  'NRT': { city: 'Tokyo', country: 'Nhật Bản', name: 'Sân bay Quốc tế Narita' },
  'NSI': { city: 'Yaoundé', country: 'Cameroon', name: 'Sân bay Quốc tế Yaoundé Nsimalen' },
  'NTE': { city: 'Nantes', country: 'Pháp', name: 'Sân bay Nantes Atlantique' },
  'NTL': { city: 'Newcastle', country: 'Úc', name: 'Sân bay Newcastle (Úc)' },
  'NUE': { city: 'Nuremberg', country: 'Đức', name: 'Sân bay Nuremberg' },
  'OAK': { city: 'Oakland', country: 'Mỹ', name: 'Sân bay Quốc tế Oakland' },
  'OKA': { city: 'Okinawa', country: 'Nhật Bản', name: 'Sân bay Naha' },
  'OKC': { city: 'Oklahoma City', country: 'Mỹ', name: 'Sân bay Thế giới Will Rogers' },
  'OKD': { city: 'Sapporo', country: 'Nhật Bản', name: 'Sân bay Okadama' },
  'OLB': { city: 'Olbia', country: 'Ý', name: 'Sân bay Olbia Costa Smeralda' },
  'OMA': { city: 'Omaha', country: 'Mỹ', name: 'Sân bay Eppley Airfield' },
  'ONT': { city: 'Ontario', country: 'Mỹ', name: 'Sân bay Quốc tế Ontario' },
  'OOL': { city: 'Gold Coast', country: 'Úc', name: 'Sân bay Gold Coast' },
  'OPO': { city: 'Porto', country: 'Bồ Đào Nha', name: 'Sân bay Francisco Sá Carneiro' },
  'ORD': { city: 'Chicago', country: 'Mỹ', name: 'Sân bay Quốc tế O\'Hare' },
  'ORF': { city: 'Norfolk', country: 'Mỹ', name: 'Sân bay Quốc tế Norfolk' },
  'ORK': { city: 'Cork', country: 'Ireland', name: 'Sân bay Cork' },
  'ORN': { city: 'Oran', country: 'Algeria', name: 'Sân bay Quốc tế Oran Es Sénia' },
  'ORY': { city: 'Paris', country: 'Pháp', name: 'Sân bay Orly' },
  'OSL': { city: 'Oslo', country: 'Na Uy', name: 'Sân bay Oslo, Gardermoen' },
  'OSS': { city: 'Osh', country: 'Kyrgyzstan', name: 'Sân bay Quốc tế Osh' },
  'OTP': { city: 'Bucharest', country: 'Romania', name: 'Sân bay Quốc tế Henri Coandă' },
  'OVB': { city: 'Novosibirsk', country: 'Nga', name: 'Sân bay Tolmachevo' },
  'PAT': { city: 'Patna', country: 'Ấn Độ', name: 'Sân bay Quốc tế Jay Prakash Narayan' },
  'PDL': { city: 'Ponta Delgada', country: 'Bồ Đào Nha', name: 'Sân bay João Paulo II' },
  'PDX': { city: 'Portland', country: 'Mỹ', name: 'Sân bay Quốc tế Portland' },
  'PEK': { city: 'Bắc Kinh', country: 'Trung Quốc', name: 'Sân bay Quốc tế Thủ Đô Bắc Kinh' },
  'PER': { city: 'Perth', country: 'Úc', name: 'Sân bay Perth' },
  'PEW': { city: 'Peshawar', country: 'Pakistan', name: 'Sân bay Quốc tế Bacha Khan' },
  'PFO': { city: 'Paphos', country: 'Síp', name: 'Sân bay Quốc tế Paphos' },
  'PHC': { city: 'Port Harcourt', country: 'Nigeria', name: 'Sân bay Quốc tế Port Harcourt' },
  'PHL': { city: 'Philadelphia', country: 'Mỹ', name: 'Sân bay Quốc tế Philadelphia' },
  'PHX': { city: 'Phoenix', country: 'Mỹ', name: 'Sân bay Quốc tế Phoenix Sky Harbor' },
  'PIT': { city: 'Pittsburgh', country: 'Mỹ', name: 'Sân bay Quốc tế Pittsburgh' },
  'PKX': { city: 'Bắc Kinh', country: 'Trung Quốc', name: 'Sân bay Quốc tế Đại Hưng Bắc Kinh' },
  'PLZ': { city: 'Port Elizabeth', country: 'Nam Phi', name: 'Sân bay Quốc tế Chief Dawid Stuurman' },
  'PMI': { city: 'Palma de Mallorca', country: 'Tây Ban Nha', name: 'Sân bay Palma de Mallorca' },
  'PMO': { city: 'Palermo', country: 'Ý', name: 'Sân bay Falcone Borsellino' },
  'PNH': { city: 'Phnom Penh', country: 'Campuchia', name: 'Sân bay Quốc tế Phnom Penh' },
  'PNK': { city: 'Pontianak', country: 'Indonesia', name: 'Sân bay Quốc tế Supadio' },
  'PNQ': { city: 'Pune', country: 'Ấn Độ', name: 'Sân bay Pune' },
  'POA': { city: 'Porto Alegre', country: 'Brazil', name: 'Sân bay Quốc tế Salgado Filho' },
  'POM': { city: 'Port Moresby', country: 'Papua New Guinea', name: 'Sân bay Quốc tế Jacksons' },
  'POS': { city: 'Port of Spain', country: 'Trinidad và Tobago', name: 'Sân bay Quốc tế Piarco' },
  'PPS': { city: 'Puerto Princesa', country: 'Philippines', name: 'Sân bay Quốc tế Puerto Princesa' },
  'PPT': { city: 'Tahiti', country: 'Polynesia thuộc Pháp', name: 'Sân bay Quốc tế Fa\'a\'ā' },
  'PQC': { city: 'Phú Quốc', country: 'Việt Nam', name: 'Sân bay Quốc tế Phú Quốc' },
  'PQQ': { city: 'Port Macquarie', country: 'Úc', name: 'Sân bay Port Macquarie' },
  'PRG': { city: 'Prague', country: 'Cộng hòa Séc', name: 'Sân bay Václav Havel Praha' },
  'PSA': { city: 'Pisa', country: 'Ý', name: 'Sân bay Quốc tế Pisa' },
  'PTP': { city: 'Pointe-à-Pitre', country: 'Guadeloupe', name: 'Sân bay Quốc tế Pointe-à-Pitre (Le Raizet)' },
  'PTY': { city: 'Panama City', country: 'Panama', name: 'Sân bay Quốc tế Tocumen' },
  'PUJ': { city: 'Punta Cana', country: 'Cộng hòa Dominica', name: 'Sân bay Quốc tế Punta Cana' },
  'PUQ': { city: 'Punta Arenas', country: 'Chile', name: 'Sân bay Quốc tế Presidente Carlos Ibáñez del Campo' },
  'PUS': { city: 'Busan', country: 'Hàn Quốc', name: 'Sân bay Quốc tế Gimhae' },
  'PVG': { city: 'Thượng Hải', country: 'Trung Quốc', name: 'Sân bay Quốc tế Phố Đông Thượng Hải' },
  'PVR': { city: 'Puerto Vallarta', country: 'Mexico', name: 'Sân bay Quốc tế Licenciado Gustavo Díaz Ordaz' },
  'PXU': { city: 'Pleiku', country: 'Việt Nam', name: 'Sân bay Pleiku' },
  'QQA': { city: 'Blaine', country: 'Mỹ', name: 'Sân bay Anoka County–Blaine' },
  'RAK': { city: 'Marrakesh', country: 'Ma-rốc', name: 'Sân bay Marrakesh Menara' },
  'RDU': { city: 'Raleigh/Durham', country: 'Mỹ', name: 'Sân bay Quốc tế Raleigh-Durham' },
  'REC': { city: 'Recife', country: 'Brazil', name: 'Sân bay Quốc tế Recife/Guararapes' },
  'REP': { city: 'Siem Reap', country: 'Campuchia', name: 'Sân bay Quốc tế Siem Reap' },
  'RGN': { city: 'Yangon', country: 'Myanmar', name: 'Sân bay Quốc tế Yangon' },
  'RHO': { city: 'Rhodes', country: 'Hy Lạp', name: 'Sân bay Quốc tế Rhodes' },
  'RIX': { city: 'Riga', country: 'Latvia', name: 'Sân bay Quốc tế Riga' },
  'RNO': { city: 'Reno', country: 'Mỹ', name: 'Sân bay Quốc tế Reno-Tahoe' },
  'RNS': { city: 'Rennes', country: 'Pháp', name: 'Sân bay Rennes–Saint-Jacques' },
  'ROA': { city: 'Roanoke', country: 'Mỹ', name: 'Sân bay Khu vực Roanoke' },
  'ROK': { city: 'Rockhampton', country: 'Úc', name: 'Sân bay Rockhampton' },
  'RST': { city: 'Rochester', country: 'Mỹ', name: 'Sân bay Quốc tế Rochester' },
  'RSW': { city: 'Fort Myers', country: 'Mỹ', name: 'Sân bay Quốc tế Southwest Florida' },
  'RTM': { city: 'Rotterdam', country: 'Hà Lan', name: 'Sân bay Rotterdam The Hague' },
  'RUH': { city: 'Riyadh', country: 'Ả Rập Xê Út', name: 'Sân bay Quốc tế King Khalid' },
  'RUN': { city: 'Saint-Denis', country: 'Reunion', name: 'Sân bay Roland Garros' },
  'SAG': { city: 'Shirdi', country: 'Ấn Độ', name: 'Sân bay Shirdi' },
  'SAL': { city: 'San Salvador', country: 'El Salvador', name: 'Sân bay Quốc tế El Salvador' },
  'SAN': { city: 'San Diego', country: 'Mỹ', name: 'Sân bay Quốc tế San Diego' },
  'SAP': { city: 'San Pedro Sula', country: 'Honduras', name: 'Sân bay Quốc tế Ramón Villeda Morales' },
  'SAT': { city: 'San Antonio', country: 'Mỹ', name: 'Sân bay Quốc tế San Antonio' },
  'SAW': { city: 'Istanbul', country: 'Thổ Nhĩ Kỳ', name: 'Sân bay Sabiha Gökçen' },
  'SCL': { city: 'Santiago', country: 'Chile', name: 'Sân bay Quốc tế Arturo Merino Benítez' },
  'SCQ': { city: 'Santiago de Compostela', country: 'Tây Ban Nha', name: 'Sân bay Santiago de Compostela' },
  'SDF': { city: 'Louisville', country: 'Mỹ', name: 'Sân bay Quốc tế Louisville' },
  'SDJ': { city: 'Sendai', country: 'Nhật Bản', name: 'Sân bay Sendai' },
  'SDQ': { city: 'Santo Domingo', country: 'Cộng hòa Dominica', name: 'Sân bay Quốc tế Las Américas' },
  'SDU': { city: 'Rio de Janeiro', country: 'Brazil', name: 'Sân bay Santos Dumont' },
  'SEA': { city: 'Seattle', country: 'Mỹ', name: 'Sân bay Quốc tế Seattle-Tacoma' },
  'SEZ': { city: 'Mahé', country: 'Seychelles', name: 'Sân bay Quốc tế Seychelles' },
  'SFO': { city: 'San Francisco', country: 'Mỹ', name: 'Sân bay Quốc tế San Francisco' },
  'SGN': { city: 'TP HCM', country: 'Việt Nam', name: 'Sân bay Quốc tế Tân Sơn Nhất' },
  'SHA': { city: 'Thượng Hải', country: 'Trung Quốc', name: 'Sân bay Quốc tế Hồng Kiều Thượng Hải' },
  'SHE': { city: 'Thẩm Dương', country: 'Trung Quốc', name: 'Sân bay Quốc tế Đào Tiên Thẩm Dương' },
  'SHJ': { city: 'Sharjah', country: 'UAE', name: 'Sân bay Quốc tế Sharjah' },
  'SIN': { city: 'Singapore', country: 'Singapore', name: 'Sân bay Quốc tế Changi' },
  'SJC': { city: 'San Jose', country: 'Mỹ', name: 'Sân bay Quốc tế Norman Y. Mineta San Jose' },
  'SJD': { city: 'Los Cabos', country: 'Mexico', name: 'Sân bay Quốc tế Los Cabos' },
  'SJO': { city: 'San José', country: 'Costa Rica', name: 'Sân bay Quốc tế Juan Santamaría' },
  'SJU': { city: 'San Juan', country: 'Puerto Rico', name: 'Sân bay Quốc tế Luis Muñoz Marín' },
  'SKG': { city: 'Thessaloniki', country: 'Hy Lạp', name: 'Sân bay Thessaloniki' },
  'SLC': { city: 'Salt Lake City', country: 'Mỹ', name: 'Sân bay Quốc tế Salt Lake City' },
  'SLL': { city: 'Salalah', country: 'Oman', name: 'Sân bay Salalah' },
  'SMF': { city: 'Sacramento', country: 'Mỹ', name: 'Sân bay Quốc tế Sacramento' },
  'SNA': { city: 'Santa Ana', country: 'Mỹ', name: 'Sân bay John Wayne' },
  'SNN': { city: 'Shannon', country: 'Ireland', name: 'Sân bay Shannon' },
  'SOF': { city: 'Sofia', country: 'Bulgaria', name: 'Sân bay Sofia' },
  'SPN': { city: 'Saipan', country: 'Bắc Mariana', name: 'Sân bay Quốc tế Francisco C. Ada' },
  'SPU': { city: 'Split', country: 'Croatia', name: 'Sân bay Split' },
  'SRG': { city: 'Semarang', country: 'Indonesia', name: 'Sân bay Quốc tế Ahmad Yani' },
  'SSA': { city: 'Salvador', country: 'Brazil', name: 'Sân bay Quốc tế Salvador' },
  'SSH': { city: 'Sharm El-Sheikh', country: 'Ai Cập', name: 'Sân bay Quốc tế Sharm El Sheikh' },
  'STN': { city: 'London', country: 'Vương quốc Anh', name: 'Sân bay London Stansted' },
  'STR': { city: 'Stuttgart', country: 'Đức', name: 'Sân bay Stuttgart' },
  'STV': { city: 'Surat', country: 'Ấn Độ', name: 'Sân bay Quốc tế Surat' },
  'SUV': { city: 'Suva', country: 'Fiji', name: 'Sân bay Quốc tế Nausori' },
  'SVG': { city: 'Stavanger', country: 'Na Uy', name: 'Sân bay Stavanger' },
  'SVO': { city: 'Moscow', country: 'Nga', name: 'Sân bay Quốc tế Sheremetyevo' },
  'SVQ': { city: 'Seville', country: 'Tây Ban Nha', name: 'Sân bay Seville' },
  'SVX': { city: 'Yekaterinburg', country: 'Nga', name: 'Sân bay Quốc tế Koltsovo' },
  'SYD': { city: 'Sydney', country: 'Úc', name: 'Sân bay Quốc tế Sydney Kingsford Smith' },
  'SYX': { city: 'Tam Á', country: 'Trung Quốc', name: 'Sân bay Quốc tế Phượng Hoàng Tam Á' },
  'SYZ': { city: 'Shiraz', country: 'Iran', name: 'Sân bay Quốc tế Shiraz' },
  'SZG': { city: 'Salzburg', country: 'Áo', name: 'Sân bay Salzburg' },
  'SZX': { city: 'Thâm Quyến', country: 'Trung Quốc', name: 'Sân bay Quốc tế Bảo An Thâm Quyến' },
  'TAE': { city: 'Daegu', country: 'Hàn Quốc', name: 'Sân bay Quốc tế Daegu' },
  'TAK': { city: 'Takamatsu', country: 'Nhật Bản', name: 'Sân bay Takamatsu' },
  'TAO': { city: 'Thanh Đảo', country: 'Trung Quốc', name: 'Sân bay Quốc tế Giao Đông Thanh Đảo' },
  'TAS': { city: 'Tashkent', country: 'Uzbekistan', name: 'Sân bay Quốc tế Islam Karimov Tashkent' },
  'TBB': { city: 'Tuy Hòa', country: 'Việt Nam', name: 'Sân bay Tuy Hòa' },
  'TBS': { city: 'Tbilisi', country: 'Georgia', name: 'Sân bay Quốc tế Tbilisi' },
  'TBU': { city: 'Nukuʻalofa', country: 'Tonga', name: 'Sân bay Quốc tế Fuaʻamotu' },
  'TFN': { city: 'Tenerife', country: 'Tây Ban Nha', name: 'Sân bay Tenerife North' },
  'TFS': { city: 'Tenerife', country: 'Tây Ban Nha', name: 'Sân bay Tenerife South' },
  'TFU': { city: 'Thành Đô', country: 'Trung Quốc', name: 'Sân bay Quốc tế Thiên Phủ Thành Đô' },
  'THD': { city: 'Thanh Hóa', country: 'Việt Nam', name: 'Sân bay Thọ Xuân' },
  'THR': { city: 'Tehran', country: 'Iran', name: 'Sân bay Quốc tế Mehrabad' },
  'TIJ': { city: 'Tijuana', country: 'Mexico', name: 'Sân bay Quốc tế Tijuana' },
  'TKN': { city: 'Tokunoshima', country: 'Nhật Bản', name: 'Sân bay Tokunoshima' },
  'TLL': { city: 'Tallinn', country: 'Estonia', name: 'Sân bay Tallinn' },
  'TLS': { city: 'Toulouse', country: 'Pháp', name: 'Sân bay Toulouse-Blagnac' },
  'TLV': { city: 'Tel Aviv', country: 'Israel', name: 'Sân bay Quốc tế Ben Gurion' },
  'TMW': { city: 'Tamworth', country: 'Úc', name: 'Sân bay Khu vực Tamworth' },
  'TNA': { city: 'Tế Nam', country: 'Trung Quốc', name: 'Sân bay Quốc tế Diêu Tường Tế Nam' },
  'TNR': { city: 'Antananarivo', country: 'Madagascar', name: 'Sân bay Quốc tế Ivato' },
  'TPA': { city: 'Tampa', country: 'Mỹ', name: 'Sân bay Quốc tế Tampa' },
  'TPE': { city: 'Đài Bắc', country: 'Đài Loan', name: 'Sân bay Quốc tế Đào Viên' },
  'TRD': { city: 'Trondheim', country: 'Na Uy', name: 'Sân bay Trondheim' },
  'TRN': { city: 'Turin', country: 'Ý', name: 'Sân bay Turin' },
  'TRV': { city: 'Thiruvananthapuram', country: 'Ấn Độ', name: 'Sân bay Quốc tế Trivandrum' },
  'TSA': { city: 'Đài Bắc', country: 'Đài Loan', name: 'Sân bay Tùng Sơn Đài Bắc' },
  'TSF': { city: 'Treviso', country: 'Ý', name: 'Sân bay Treviso (S. Angelo)' },
  'TSN': { city: 'Thiên Tân', country: 'Trung Quốc', name: 'Sân bay Quốc tế Tân Hải Thiên Tân' },
  'TSV': { city: 'Townsville', country: 'Úc', name: 'Sân bay Townsville' },
  'TUN': { city: 'Tunis', country: 'Tunisia', name: 'Sân bay Quốc tế Tunis-Carthage' },
  'TUS': { city: 'Tucson', country: 'Mỹ', name: 'Sân bay Quốc tế Tucson' },
  'TXG': { city: 'Đài Trung', country: 'Đài Loan', name: 'Sân bay Quốc tế Đài Trung' },
  'TYN': { city: 'Thái Nguyên', country: 'Trung Quốc', name: 'Sân bay Quốc tế Vũ Túc Thái Nguyên' },
  'UIH': { city: 'Quy Nhơn', country: 'Việt Nam', name: 'Sân bay Phù Cát' },
  'UIO': { city: 'Quito', country: 'Ecuador', name: 'Sân bay Quốc tế Mariscal Sucre' },
  'UKB': { city: 'Kobe', country: 'Nhật Bản', name: 'Sân bay Kobe' },
  'URC': { city: 'Urumqi', country: 'Trung Quốc', name: 'Sân bay Quốc tế Diwopu Ürümqi' },
  'URT': { city: 'Surat Thani', country: 'Thái Lan', name: 'Sân bay Surat Thani' },
  'USM': { city: 'Koh Samui', country: 'Thái Lan', name: 'Sân bay Samui' },
  'VCA': { city: 'Cần Thơ', country: 'Việt Nam', name: 'Sân bay Quốc tế Cần Thơ' },
  'VCE': { city: 'Venice', country: 'Ý', name: 'Sân bay Venice Marco Polo' },
  'VCL': { city: 'Chu Lai', country: 'Việt Nam', name: 'Sân bay Chu Lai' },
  'VCP': { city: 'Campinas', country: 'Brazil', name: 'Sân bay Quốc tế Viracopos' },
  'VCS': { city: 'Côn Đảo', country: 'Việt Nam', name: 'Sân bay Côn Đảo' },
  'VDO': { city: 'Vân Đồn', country: 'Việt Nam', name: 'Sân bay Quốc tế Vân Đồn' },
  'VDZ': { city: 'Côn Đảo', country: 'Việt Nam', name: 'Sân bay Côn Đảo' },
  'VIE': { city: 'Vienna', country: 'Áo', name: 'Sân bay Quốc tế Vienna' },
  'VII': { city: 'Vinh', country: 'Việt Nam', name: 'Sân bay Quốc tế Vinh' },
  'VKG': { city: 'Rạch Giá', country: 'Việt Nam', name: 'Sân bay Rạch Giá' },
  'VKO': { city: 'Moscow', country: 'Nga', name: 'Sân bay Quốc tế Vnukovo' },
  'VLC': { city: 'Valencia', country: 'Tây Ban Nha', name: 'Sân bay Valencia' },
  'VLI': { city: 'Port Vila', country: 'Vanuatu', name: 'Sân bay Quốc tế Bauerfield' },
  'VNO': { city: 'Vilnius', country: 'Lithuania', name: 'Sân bay Quốc tế Vilnius' },
  'VNS': { city: 'Varanasi', country: 'Ấn Độ', name: 'Sân bay Quốc tế Lal Bahadur Shastri' },
  'VRN': { city: 'Verona', country: 'Ý', name: 'Sân bay Verona Villafranca' },
  'VTE': { city: 'Viêng Chăn', country: 'Lào', name: 'Sân bay Quốc tế Wattay' },
  'VVI': { city: 'Santa Cruz', country: 'Bolivia', name: 'Sân bay Quốc tế Viru Viru' },
  'WAW': { city: 'Warsaw', country: 'Ba Lan', name: 'Sân bay Warsaw Chopin' },
  'WLG': { city: 'Wellington', country: 'New Zealand', name: 'Sân bay Quốc tế Wellington' },
  'WMT': { city: 'Tuân Nghĩa', country: 'Trung Quốc', name: 'Sân bay Mao Đài Tuân Nghĩa' },
  'WNZ': { city: 'Ôn Châu', country: 'Trung Quốc', name: 'Sân bay Quốc tế Long Loan Ôn Châu' },
  'WRO': { city: 'Wrocław', country: 'Ba Lan', name: 'Sân bay Copernicus Wrocław' },
  'WUH': { city: 'Vũ Hán', country: 'Trung Quốc', name: 'Sân bay Quốc tế Thiên Hà Vũ Hán' },
  'XIC': { city: 'Tây Xương', country: 'Trung Quốc', name: 'Sân bay Thanh Sơn Tây Xương' },
  'XIY': { city: 'Tây An', country: 'Trung Quốc', name: 'Sân bay Quốc tế Hàm Dương Tây An' },
  'XMN': { city: 'Hạ Môn', country: 'Trung Quốc', name: 'Sân bay Quốc tế Cao Khi Hạ Môn' },
  'YEG': { city: 'Edmonton', country: 'Canada', name: 'Sân bay Quốc tế Edmonton' },
  'YHZ': { city: 'Halifax', country: 'Canada', name: 'Sân bay Quốc tế Halifax Stanfield' },
  'YOW': { city: 'Ottawa', country: 'Canada', name: 'Sân bay Quốc tế Ottawa Macdonald-Cartier' },
  'YQB': { city: 'Thành phố Québec', country: 'Canada', name: 'Sân bay Quốc tế Québec City Jean Lesage' },
  'YTZ': { city: 'Toronto', country: 'Canada', name: 'Sân bay Billy Bishop Toronto City' },
  'YUL': { city: 'Montréal', country: 'Canada', name: 'Sân bay Quốc tế Montréal-Pierre Elliott Trudeau' },
  'YVR': { city: 'Vancouver', country: 'Canada', name: 'Sân bay Quốc tế Vancouver' },
  'YWG': { city: 'Winnipeg', country: 'Canada', name: 'Sân bay Quốc tế Winnipeg James Armstrong Richardson' },
  'YYC': { city: 'Calgary', country: 'Canada', name: 'Sân bay Quốc tế Calgary' },
  'YYZ': { city: 'Toronto', country: 'Canada', name: 'Sân bay Quốc tế Toronto Pearson' },
  'ZAG': { city: 'Zagreb', country: 'Croatia', name: 'Sân bay Zagreb' },
  'ZAZ': { city: 'Zaragoza', country: 'Tây Ban Nha', name: 'Sân bay Zaragoza' },
  'ZIA': { city: 'Moscow', country: 'Nga', name: 'Sân bay Quốc tế Zhukovsky' },
  'ZNZ': { city: 'Zanzibar', country: 'Tanzania', name: 'Sân bay Quốc tế Abeid Amani Karume' },
  'ZQN': { city: 'Queenstown', country: 'New Zealand', name: 'Sân bay Queenstown' },
  'ZRH': { city: 'Zurich', country: 'Thụy Sĩ', name: 'Sân bay Zurich' }
};